FROM ubuntu:22.10

RUN sudo apt-get update && \
    sudo apt-get install -y mesa-common-dev \
                            libxrandr-dev \
                            libxinerama-dev \
                            libxcursor-dev \
                            libxi-dev \
                            libgl1-mesa-dev \
                            x11proto-core-dev \
                            libx11-dev \
                            libstdc++-10-dev \
                            libopengl-dev \
                            libglu1-mesa-dev \
                            freeglut3-dev && \
    sudo apt-get upgrade -y